//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public System.Guid StudentID { get; set; }
        public string StudentName { get; set; }
        [Required]
        [EmailAddress]
        public string StudentEmail { get; set; }
        public string Course { get; set; }
        public string Department { get; set; }
    }
}
